package com.fqueue.domain;
//Generated Dec 18, 2008 10:51:11 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * ProcessId generated by hbm2java
 */

public class ProcessId  implements java.io.Serializable {


	// Fields    

	private int no;
	private Date time;


	// Constructors

	/** default constructor */
	public ProcessId() {
	}


	/** full constructor */
	public ProcessId(int no, Date time) {
		this.no = no;
		this.time = time;
	}



	// Property accessors

	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}




	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof ProcessId) ) return false;
		ProcessId castOther = ( ProcessId ) other; 

		return (this.getNo()==castOther.getNo())
		&& ( (this.getTime()==castOther.getTime()) || ( this.getTime()!=null && castOther.getTime()!=null && this.getTime().equals(castOther.getTime()) ) );
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNo();
		result = 37 * result + ( getTime() == null ? 0 : this.getTime().hashCode() );
		return result;
	}
}